### ISSUE TITLE
So how to receive and send  WeChat messages with telegram?

### ISSUE THREAD

**Issue by rogepi** [MatrixLau/efb-solitaire_optimize-middleware#5]
So how to receive and send  WeChat messages with telegram?

**Comment by MatrixLau** [comment]
Should've follow this project [https://github.com/ehForwarderBot/ehForwarderBot](url)

**Comment by MatrixLau** [comment]
Should've seen [this project](https://github.com/ehForwarderBot/ehForwarderBot)
