### ISSUE TITLE
如果接龙有人对中间的接龙信息进行了更新，会产生新的接龙消息

### ISSUE THREAD

**Issue by QQ-War** [MatrixLau/efb-solitaire_optimize-middleware#7]
这个估计要改改逻辑了，现在的逻辑只处理最新往下加的。

**Comment by MatrixLau** [comment]
同时抢一个号码的时候也会，但我提这个这个跟不同机子网络延迟也有关，所以很难解决，你的这个问题的话因为微信其实接龙也是没有一个标识的，中间人改了一个之前是想写的，但是出的问题也不少就搁置了
